kind: pipeline
type: kubernetes
name: package-helm-chart
platform:
  os: linux
  arch: amd64
steps:
  - name: package-helm
    image: alpine/helm:3.16
    commands:
      - helm package .
    when:
      event:
        - tag
  - name: update-index
    image: alpine/helm:3.16
    commands:
      - helm repo index . --url https://github.com/UKHomeOffice/inquiry-charts/releases/download/$${DRONE_TAG}/
      - cat index.yaml
    when:
      event:
        - tag
  - name: create-pull-request
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - git config user.name "drone-ci"
      - git config user.email "drone-ci@no-reply.com"
      - apk add --no-cache curl jq
      - chmod +x ./create_pr.sh
      - ./create_pr.sh "$GITHUB_TOKEN"
    when:
      event:
        - tag
  - name: attach-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: "*.tgz"
    when:
      event:
        - tag
  - name: cleanup
    image: alpine
    commands:
      - rm -rf *.tgz
trigger:
  event:
    - tag