kind: pipeline
type: kubernetes
name: package-helm-chart
platform:
  os: linux
  arch: amd64
steps:
  - name: update-chart-version
    image: alpine
    commands:
      - |
        sed -i "s/^version:.*/version: ${DRONE_TAG}/" Chart.yaml
        sed -i "s/^appVersion:.*/appVersion: ${DRONE_TAG}/" Chart.yaml
      - cat Chart.yaml
    when:
      event:
        - tag
  - name: package-helm
    image: alpine/helm:3.16
    commands:
      - helm package .
    when:
      event:
        - tag
  - name: update-index
    image: alpine/helm:3.16
    commands:
      - helm repo index . --url https://github.com/UKHomeOffice/inquiry-charts/releases/download/$${DRONE_TAG}/
      - cat index.yaml
    when:
      event:
        - tag
  - name: push-branch
    image: alpine/git
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - git config user.name "drone-ci"
      - git config user.email "drone-ci@no-reply.com"
      - git checkout -b "update-chart-${DRONE_TAG}"
      - git add Chart.yaml index.yaml
      - git commit -m "Update Helm chart version to ${DRONE_TAG}"
      - echo "Changes committed to the new branch"
      - git push "https://${GITHUB_TOKEN}@github.com/UKHomeOffice/inquiry-charts.git" "update-chart-${DRONE_TAG}"
    when:
      event:
        - tag
  - name: create-pull-request
    image: curlimages/curl:7.73.0
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - >
        curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
        -d '{"title":"Update Helm chart version to '${DRONE_TAG}'", "head":"update-chart-'${DRONE_TAG}'", "base":"main"}' \
        https://api.github.com/repos/UKHomeOffice/inquiry-charts/pulls
    when:
      event:
        - tag
  - name: attach-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: "*.tgz"
    when:
      event:
        - tag
  - name: cleanup
    image: alpine
    commands:
      - rm -rf *.tgz
trigger:
  event:
    - tag