apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    name: {{ .Values.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
