apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-admin
  labels: 
    {{- with .Values.admin.labels }}
    {{ toYaml . }}
    {{- end }}
  annotations:
    downscaler/uptime: {{ .Values.admin.uptime }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      {{- include "adminSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        role: wordpress
        {{- include "adminSelectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.admin.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.shortName }}-wordpress
          image: "{{ required "No image specified. A valid image.repository is required!" .Values.admin.image.repository }}:{{ required "A valid image.tag is required!" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          livenessProbe:
             httpGet:
               path: /
               port: 8081
             initialDelaySeconds: 90
             periodSeconds: 20
             timeoutSeconds: 10
             failureThreshold: 4
             successThreshold: 1
          readinessProbe:
             httpGet:
               path: /
               port: 8081
             initialDelaySeconds: 90
             periodSeconds: 30
             timeoutSeconds: 10
             failureThreshold: 4
             successThreshold: 1
          resources:
            {{- toYaml .Values.admin.resources | nindent 12 }}
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-config-admin
          env:
           {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .valueFrom.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- else if .value }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}
      {{- with .Values.admin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

