apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}
  labels:
    cert-manager.io/solver: http01
spec:
  secretName: {{ required "provide a secret name for admin cert" .Values.admin.secretName }}
  issuerRef:
    # use letsencrypt-staging while developing and testing your certificates
    name: {{ .Values.admin.certificate.issuerName | default "letsencrypt-prod" }}
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    {{- toYaml .Values.admin.certificate.dnsNames | nindent 4 }}