apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-network-policy-{{ .Values.shortName }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  policyTypes:
  {{- range .Values.networkPolicy.policyTypes }}
    - {{ . }}
  {{- end }}

  {{- if (has "Ingress" .Values.networkPolicy.policyTypes) }}
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - from:
        {{- if .from }}
          {{- range .from }}
        - namespaceSelector:
            matchLabels:
              name: {{ .namespaceSelector.matchLabels.name }}
          {{- end }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  {{- end }}

  {{- if (has "Egress" .Values.networkPolicy.policyTypes) }}
  egress:
      {{- range .Values.networkPolicy.egress }}
    - to:
          {{- if .to }}
            {{- range .to }}
        - namespaceSelector: {{ .namespaceSelector | default "{}" }}
            {{- end }}
          {{- end }}
      ports:
          {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
          {{- end }}
      {{- end }}
    {{- end }}