apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-network-policy-{{ .Values.shortName }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-external
      ports:
        - protocol: TCP
          port: 8081
        {{- if .Values.static.enabled }}
        - protocol: TCP
          port: 8080
        {{- end }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
        - port: 3306
          protocol: TCP
        - port: 443
          protocol: TCP
    - to:
        - namespaceSelector: {}