{{- if .Values.static.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-nginx
  labels:
    {{- with .Values.static.nginx.labels }}
    {{ toYaml . }}
    {{- end }}
  annotations:
    downscaler/uptime: {{ .Values.static.nginx.uptime }}
spec:
  replicas: {{ .Values.static.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        role: nginx
        app: {{ .Values.name }}
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.static.nginx.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.shortName }}-nginx
          image: "{{ required "A valid image.repository is required!" .Values.static.nginx.image.repository }}:{{ required "A valid image.tag is required!" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.static.nginx.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 4
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 4
            successThreshold: 1
          resources:
            {{- toYaml .Values.static.nginx.resources | nindent 12 }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: static-files
              mountPath: "/var/www/html"
              readOnly: true
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-staticfiles-data-claim
      {{- with .Values.static.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.static.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.static.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}