{{- if .Values.static.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-nginx
spec:
  selector:
    name: {{ .Values.name }}-nginx
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{- end }}