{{- if .Values.static.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-syncstatic-data-claim
  labels:
    project: {{ .Values.name }}
    {{- with .Values.static.pvc.labels }}
    {{ toYaml . }}
    {{- end }}
spec:
  storageClassName: {{ .Values.static.pvc.syncstatic.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.static.pvc.syncstatic.storage }}
{{- end }}