{{- if .Values.tools.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-client
  template:
    metadata:
      labels:
        app: mysql-client
    spec:
      containers:
        - name: mysql-client
          image: quay.io/ukhomeofficedigital/inquiry-tools:latest
          command: ["sleep"]
          args: ["infinity"] # Keeps the pod running
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
{{- end }}