apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  {{- if .Values.prod }}
  name: {{ .Values.name }}-prod
  {{ else }}
  name: {{ .Values.name }}
  {{- end }}
  labels:
    cert-manager.io/solver: http01
spec:
  secretName: {{ required "provide a secret name for wordpress cert" .Values.wordpress.secretName }}
  issuerRef:
    name: {{ .Values.wordpress.certificate.issuerName | default "letsencrypt-prod" }}
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    {{- toYaml .Values.wordpress.certificate.dnsNames | nindent 4 }}